### PR TITLE
REALMC-8671: update goja to latest

### PR DESCRIPTION
**Pull request by Gabri3l**
These changes have technically been reviewed before but I had to revert them because tests were failing in `baas`. The last two commits are the ones that possibly fixed the failing test suites. Nothing stops you from still giving it another look by all means!

### CODE REVIEW

**Review by tsedgwick — APPROVED** [review]
🏖️

**Comment by Gabri3l** [comment]
I should specify that this PR won't get merged until evergreen is OK with [REALMC-8671](https://github.com/10gen/baas/pull/4291) in baas.

**Review by arahmanan — APPROVED** [review]
LGTM!

**Comment by Gabri3l** [comment]
Sorry for pinging y'all again @tsedgwick @arahmanan but I updated the memory usage tests to include the stack and added comments on some values. 

Didn't get a chance to dig into how the stack is managed but some memory usage calculations were pretty straightforward others were a bit more unintuitive (things get pulled OUT of the stack and new things get pushed into the stack so certain values represent the difference between the two calls to `checkMem()`)

**Review by arahmanan — APPROVED** [review]
LGTM!

**Pull request merged**
