### PR TITLE
BAAS-24673: Implement String.prototype.replaceAll

### PR DESCRIPTION
**Pull request by Calvinnix**
(cherry picked from commit 6df49a26cb0c465a051b7773f6b27b81685d7d63)

### CODE REVIEW

**Comment by Calvinnix** [comment]
Is this the normal format when cherry-picking a commit from upstream?

**Comment by Gabri3l** [comment]
We respect the usual `BAAS-XXXX: do something` format even when pulling commits from upstream

**Review by Gabri3l — APPROVED** [review]
Nice, pending the PR title change! This brings me so much joy ahah

**Review by arahmanan — APPROVED** [review]
LGTM!

**Pull request merged**
