### PR TITLE
BAAS-24694: Safely handle empty fromEntries values

### PR DESCRIPTION
**Pull request by UnicodeSnowman**
Currently, `Object.fromEntries` calls will panic for empty entries due to the fact that `toPropertyKey` blindly calls `key.toString()` without checking if `key` is nil:

```javascript
Object.fromEntries([
    ['a', 123], 
    ['b', 456], 
]) // => { a: 123, b: 456 }

Object.fromEntries([
    ['a', 123], // safe
    [], // panic!
    ['b', 456], 
]) // should be => { a: 123, undefined: undefined, b: 456 }
```

Goja provides an existing `nilSafe` method that returns `_undefined` for `nil` values, so I've gone ahead and used that. 

~Planning on submitting a PR upstream to goja to fix this, but figured it would be faster to just handle this here first.~

EDIT: nevermind, I didn't realize that we were the ones that added the `fromEntries` tests, `nilSafe` function, etc. 🙄

### CODE REVIEW

**Review by Gabri3l — APPROVED** [review]
Sweeet!

**Review by jwongmongodb — APPROVED** [review]
LGTM! nice catch

**Comment by Gabri3l** [comment]
Also don't worry about the github actions failing for now, that's "normal" and we have a plan in place to fix it!

**Review by LijieZhang1998 — APPROVED** [review]
LGTM 💯

**Pull request merged**
