### PR TITLE
REALMC-11774: support conversion to JS Uint8Array from a Go byte slice

### PR DESCRIPTION
**Pull request by asudhakal**
_Note: I've added a simple commit for now to get this PR up and running._ 

There are a few approaches we can take here to support this conversion (please let me know if there's a better solution that I've missed). Wanted to get this conversation going and get everyone's thoughts! Some background on why we need this: 

In [`lib_http_parser.go`](https://github.com/10gen/baas/blob/master/function/execution/vm/lib_http_parser.go#L394), we call the [`parserOnBody`](https://github.com/10gen/baas/blob/master/function/execution/common/nodejs_standard_libraries/_http_common.js#L106) function in `_http_common.js`. We end up converting the passed in [`body []byte`](https://github.com/10gen/baas/blob/master/function/execution/vm/lib_http_parser.go#L394) as a [`reflect.Slice`](https://github.com/mongodb-forks/goja/blob/realm/runtime.go#L1823) type in the `ToValue` function in goja within [`CallWithContext`](https://github.com/10gen/baas/blob/master/function/execution/vm/vm_goja.go#L306). This implementation requires us to [add this diversion](https://github.com/10gen/baas/blob/master/function/execution/common/nodejs_standard_libraries/_http_common.js#L114), which is adding 6-8 seconds to our HTTPS (and `axios`) requests (for larger response payloads). 

Converting the `[]byte` that we pass in to `CallWithContext` into a `Uint8Array` object directly from goja instead of using `Buffer.From` reduces the request time of HTTPS from 8-12s to 1-1.5s (5mb payload). 

The brute force solution would be to add a new type to [this switch statement](https://github.com/mongodb-forks/goja/blob/realm/runtime.go#L1665), specifically of type `[]uint8` which the passed in `[]byte` satisfies: 

```
case []uint8:
	buf := r._newArrayBuffer(r.global.ArrayBufferPrototype, nil)
	buf.data = i
	o := &Object{runtime: r}
	a := r.newUint8ArrayObject(buf, 0, len(buf.data), r.global.Uint8Array)
	o.self = a
	a.init()
	return o
```

This can cause issues to other dependencies however. After initial testing, `fs.ReadFileSync` broke since it also passes in `[]byte` to `CallWithContext`. Going down this route may lead to more issues and thus more debugging time on our end with new dependencies. 

Another solution would be to create a `NewUint8ArrayObject` function [here](https://github.com/mongodb-forks/goja/blob/realm/typedarrays.go), and also create a specific `CallWithContextHTTP` (or something along those lines) that adds a type case within its switch statement. 

`goja/typedarrays.go`

```
func (r *Runtime) NewUint8ArrayObject(data []byte) *Object {
	buf := r._newArrayBuffer(r.global.ArrayBufferPrototype, nil)
	buf.data = data
	o := &Object{runtime: r}
	a := r.newUint8ArrayObject(buf, 0, len(buf.data), r.global.Uint8Array)
	o.self = a
	a.init()
	return o
}
```

`function/execution/vm/vm_goja.go`

```
func (g *gojaVM) CallWithContextHTTP(ctx context.Context, this interface{}, f interface{}, args ...interface{}) (funcexecmodels.JSValue, error) {
	...

	convertedArgs := make([]goja.Value, 0, len(args))
	for _, arg := range args {
		var a goja.Value
		switch x := arg.(type) {
		case goja.Value:
			if gObj, ok := x.(*gojaObject); ok {
				a = gObj.Object
			} else {
				a = x
			}
		case jsFunc:
			a = g.vm.ToValue(gojaFunc(x))

                // new switch case
		case []uint8:
			a = g.vm.NewUint8ArrayObject(x)
		
                default:
			a = g.vm.ToValue(x)
		}
		convertedArgs = append(convertedArgs, a)
	}

	return fn(ctx, obj, convertedArgs...)
}
```

While this does solve the issue with slow http requests for now, we seem to bypass the underlying problem of other [performance related issues](https://jira.mongodb.org/browse/REALMC-11795) that we have planned to address [later in this epic](https://docs.google.com/document/d/1e2xm2CxRoYOvhmBSmA4qKlCwJaW2QtolzdpX4He55mI/edit). If the performance related issues solve slow http requests, we can then revert these changes.

### CODE REVIEW

**Comment by Gabri3l** [comment]
I think what's relevant to note here is that this performance issue for http requests from [this diversion](https://github.com/10gen/baas/blob/master/function/execution/common/nodejs_standard_libraries/_http_common.js#L114) is because of the poor performance of our `for` loops. In this case since the input is already a `byte` array, its conversion to `uint8` is an identity operation but we still loop through all of it. When our iterations grow with an increasing payload size this `for` loops takes longer and longer. With this approach we would just skip this altogether and provide the already-converted buffer to js-land.

As @asudhakal mentions this basically gives us time to find a better way to handle long `for` loops while providing better performance for some async requests with bigger payloads.

**Comment by tsedgwick** [comment]
> I think what's relevant to note here is that this performance issue for http requests from [this diversion](https://github.com/10gen/baas/blob/master/function/execution/common/nodejs_standard_libraries/_http_common.js#L114) is because of the poor performance of our `for` loops. In this case since the input is already a `byte` array, its conversion to `uint8` is an identity operation but we still loop through all of it. When our iterations grow with an increasing payload size this `for` loops takes longer and longer. With this approach we would just skip this altogether and provide the already-converted buffer to js-land.
> 
> As @asudhakal mentions this basically gives us time to find a better way to handle long `for` loops while providing better performance for some async requests with bigger payloads.

Does this warrant a comment in code vs on the PR?

**Comment by Gabri3l** [comment]
Oh yeah this will 100% live in code as well

**Comment by arahmanan** [comment]
Good find @asudhakal! 

> While this does solve the issue with slow http requests for now, we seem to bypass the underlying problem of other [performance related issues](https://jira.mongodb.org/browse/REALMC-11795) that we have planned to address [later in this epic](https://docs.google.com/document/d/1e2xm2CxRoYOvhmBSmA4qKlCwJaW2QtolzdpX4He55mI/edit). If the performance related issues solve slow http requests, we can then revert these changes.

I'm not sure I understand how [REALMC-11795](https://jira.mongodb.org/browse/REALMC-11795) and this ticket are related. Do you mind elaborating on that?
@Gabri3l which `for` loop are you referring to? Are you talking about JS `for` loops?

**Comment by asudhakal** [comment]
> 

We go through[ this ](https://github.com/Gabri3l/buffer/blob/master/index.js#L259)for loop within the `Buffer` module. The number of iterations of a 5 mb response size is around 7 million, and is taking 5-6 seconds to execute.

**Comment by arahmanan** [comment]
Interesting! I think the safest option would be to create the `NewUint8ArrayObject` function you suggested and provide that object directly to the `CallWithContext` function. Would that work?

**Comment by arahmanan** [comment]
@asudhakal for reference, we rate limit applications that perform more than 5M ticks per second. I believe increasing [this value](https://github.com/10gen/baas/blob/1aa5c5c1a75bb16e42ed32d8a7cac5d418b644ba/common/limits.go#L26) would improve the execution time of the functions mentioned in [REALMC-11795](https://jira.mongodb.org/browse/REALMC-11795).

**Comment by asudhakal** [comment]
> Interesting! I think the safest option would be to create the `NewUint8ArrayObject` function you suggested and provide that object directly to the `CallWithContext` function. Would that work?

@arahmanan 
If my understanding is correct, that should work for goja, since we could create a `ByteSliceToUint8Array(data []byte) *goja.Object` function within `vm_goja.go`, call that directly in `lib_http_parser.go` and then pass that object into `CallWithContext`. But since `vm_goja` implements `vm.go` we'd also have to create a way for Otto to implement the new `ByteSliceToUint8Array` function.

**Comment by arahmanan** [comment]
@asudhakal for the otto implementation, would something along these lines work?
```
func (o *ottoVM) ToUint8Array(data []byte) (funcexecmodels.JSValue, error) {
  src := `function(data, len) {
      return Buffer.from(data, 0, len);
  }`
  
  convFunc, err := o.vm.Run(src)
  if !convFunc.IsFunction() {
	return nil, errors.New(...)
  }

  return convFunc.Call(otto.Value{}, data, len(data))
}
```

**Comment by asudhakal** [comment]
@Gabri3l @arahmanan 

**Changes**:
- Create a new `NewUint8Array` constructor in goja (this PR)
- Create a new `ToUint8Array` conversion func in `vm.go` of type: ```ToUint8Array(data []byte) (funcexecmodels.JSValue, error)```

Otto Implementation: 
```
func (o *ottoVM) ToUint8Array(data []byte) (funcexecmodels.JSValue, error) {
	src := `function(data, len) {
		return Buffer.from(data, 0, len);
	}`

	convFunc, _ := o.vm.Run(src)
	if !convFunc.IsFunction() {
		return nil, fmt.Errorf("%T is not a function", convFunc)
	}

	return convFunc.Call(otto.Value{}, data, len(data))
}
```

Goja Implementation:
```
func (g *gojaVM) ToUint8Array(data []byte) (funcexecmodels.JSValue, error) {
	return g.vm.NewUint8ArrayObject(data), nil
}
```

We will then call `ToUint8Array` in [`lib_http_parser.go`](https://github.com/10gen/baas/blob/b424bff4f6b4b04691ee5e65fe74e0519eb2eb7d/function/execution/vm/lib_http_parser.go#L387) and pass in the object into `CallWithContext`.

**Comment by Gabri3l** [comment]
> @Gabri3l @arahmanan
> 
> Verdict seems to be as outlined below, please let me know if there's something missing here.
> 
> **Changes**:
> 
>     * Create a new `NewUint8Array` constructor in goja (this PR)
> 
>     * Create a new `ToUint8Array` conversion func in `vm.go` of type: `ToUint8Array(data []byte) (funcexecmodels.JSValue, error)`
> 
> 
> Otto Implementation:
> 
> ```
> func (o *ottoVM) ToUint8Array(data []byte) (funcexecmodels.JSValue, error) {
> 	src := `function(data, len) {
> 		return Buffer.from(data, 0, len);
> 	}`
> 
> 	convFunc, _ := o.vm.Run(src)
> 	if !convFunc.IsFunction() {
> 		return nil, fmt.Errorf("%T is not a function", convFunc)
> 	}
> 
> 	return convFunc.Call(otto.Value{}, data, len(data))
> }
> ```
> 
> Goja Implementation:
> 
> ```
> func (g *gojaVM) ToUint8Array(data []byte) (funcexecmodels.JSValue, error) {
> 	return g.vm.NewUint8ArrayObject(data), nil
> }
> ```
> 
> We will then call `ToUint8Array` in [`lib_http_parser.go`](https://github.com/10gen/baas/blob/b424bff4f6b4b04691ee5e65fe74e0519eb2eb7d/function/execution/vm/lib_http_parser.go#L387) and pass in the object into `CallWithContext`.

Sounds good to me, pretty minimal changes I like it!

**Review by Gabri3l — APPROVED** [review]

**Review by arahmanan — APPROVED** [review]
nice! LGTM!

**Pull request merged**
