### PR TITLE
BAAS-22176: bump to v2

### PR DESCRIPTION
**Pull request by Gabri3l**

### CODE REVIEW

**Review by kpatel71716 — COMMENTED** [review]
[q] could we could make a v2 tag from the `realm` branch? Or is the intention to start versioning each of the individual packages for more granular versioning?

Not opposed to either approach, just curious. If we are going with the latter, this lgtm

**Comment by Gabri3l** [comment]
> [q] could we could make a v2 tag from the `realm` branch? Or is the intention to start versioning each of the individual packages for more granular versioning?
> 
> Not opposed to either approach, just curious. If we are going with the latter, this lgtm

Still doing the tags, IIUC you gotta do this for major versions in go. From `baas` I can't just use v2.0.0 I have to use goja/v2 v2.0.0 which is why this PR is needed. We can still go back ahah

**Comment by kpatel71716** [comment]
> Still doing the tags, IIUC you gotta do this for major versions in go. From `baas` I can't just use v2.0.0 I have to use goja/v2 v2.0.0 which is why this PR is needed. We can still go back ahah

Ah, TIL, works for me then!

**Review by kpatel71716 — APPROVED** [review]
LGTM!

**Comment by Gabri3l** [comment]
Won't do, I don't think this is worth it every time we make a breaking change to the mem usage. It might also conflict with an eventual v2 of goja and make things confusing.

**Pull request closed without merging**
